language: julia
os:
  - linux
  - windows
  # - osx
julia:
  - 1.0
  - 1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - julia --color=yes -e 'using Pkg; if VERSION >= v"1.1.0-rc1"; Pkg.build(verbose=true); else Pkg.build(); end'
  - julia --color=yes -e 'using Pkg; if VERSION >= v"1.3"; Pkg.precompile(); else Pkg.API.precompile(); end'
  - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'
